const history = require('connect-history-api-fallback');
const express = require('express');
const path = require('path');
const serveStatic = require('serve-static');
app = express();
app.use(history());
app.use(serveStatic(__dirname + "/dist"));
var port = process.env.PORT || 4200;
app.listen(port);
console.log('server started '+ port);